 - name: Install redis
  ansible.builtin.dnf:
    name: redis
    state: present

- name: Allow remote connections
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start and enable redis 
  ansible.builtin.service:
    name: redis
    state: restarted
    enabled: yes


