- name: app set up
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: java
  ansible.builtin.import_role:
    name: common
    tasks_from: java

- name: mysql setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql-setup

- name: systemctl service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd