- name: app set up
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: go
  ansible.builtin.import_role:
    name: common
    tasks_from: go

- name: systemctl service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd